### PR TITLE
Properly support Laravel 6.x

### PR DESCRIPTION
**Pull request by jkudish**
Hi there,

I'm attempting to use this package with Laravel 6.x (latest version is 6.5 as of today),  but the version constraint that was added doesn't respect Laravel's new adoption of semver.

Laravel 6.x now uses semver, so we need to support 6.1, 6.2, etc.

### CODE REVIEW

**Comment by wouterNL** [comment]
Could up the version and ill merge it in.

**Comment by jkudish** [comment]
@wouterNL sorry what do you mean by up the version?

**Comment by wouterNL** [comment]
Line 5 of the composer json

**Comment by jkudish** [comment]
Gotcha, done! 

Not sure if you wanted to go to 1.1.11 or 1.2 but I went with 1.2

**Comment by jkudish** [comment]
Thanks for the merge

**Comment by wouterNL** [comment]
No worries! Thanks for updating the version! Look for 1.2 in your composer json in your project

**Pull request merged**
